### ISSUE TITLE
Relative paths

### ISSUE THREAD

**Issue by Ilium77** [mmohamed/velero-dashboard#4]
Hi,
first of all, great job :)

Is it possible to make relative paths for href so I can use traefik (instead of Ingress) with stripprefix : https://doc.traefik.io/traefik/middlewares/http/stripprefix/

Or add the possibility to use a subdomain.

Thanks !

**Comment by mmohamed** [comment]
Hi,

I understand the issue,  can you use this images : medinvention/my-velero-dashboard:1.1.3-rc and add an environment variable APP_SUB_PATH to set the subpath of your app.

Can you test it and confirm that work properly before merging the feature ?

Refer @https://github.com/mmohamed/velero-dashboard/tree/feat/sub-path#:~:text=APP_SUB_PATH%3D/myapp%20%23%20no%20default

**Comment by Ilium77** [comment]
Hi,

it's perfect ! Thank you very much !
